# Spring Boot Application Configuration

# Application Name: Defines the name of the Spring Boot application, used for logging, metrics, and application identification
spring.application.name=workflow-service

# Database Configuration
# Database URL: JDBC connection string for connecting to the PostgreSQL database hosted on localhost at port 5432, database name 'ems'
spring.datasource.url=jdbc:postgresql://localhost:5432/ems
# Database Username: Username for authenticating with the PostgreSQL database
spring.datasource.username=postgres
# Database Password: Password for authenticating with the PostgreSQL database
spring.datasource.password=1234

# JPA/Hibernate Configuration
# Hibernate DDL Auto: Automatically creates or updates the database schema based on JPA entity mappings (options: create, create-drop, update, validate, none)
spring.jpa.hibernate.ddl-auto=update
# Show SQL: Enables logging of all SQL statements executed by Hibernate for debugging purposes
spring.jpa.show-sql=true
# Format SQL: Pretty-prints the SQL statements in the logs for better readability
spring.jpa.properties.hibernate.format_sql=true
# Hibernate Dialect: Specifies the SQL dialect to use for PostgreSQL, optimizing SQL generation for the database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
